name: Deploy Backend to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow when you push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Backend Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Set Python version for backend

    # Optional: Install dependencies directly in GitHub Actions if needed, but if it's handled in Dockerfile, this step can be removed.
    # - name: Install Dependencies
    #   run: |
    #     pip install -r requirements.txt  # Install backend dependencies

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image (Backend)
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: SSH into EC2 and Deploy Backend
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.AWS_EC2_IP }} << 'EOF'
          # Create shared network if not exists
          docker network create app-network || true
          
          # Deploy backend
          docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest
          docker stop backend || true
          docker rm backend || true
          docker run -d \
            --name backend \
            --network app-network \
            -p 8000:8000 \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -e DEBUG=False \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_USER="${{ secrets.DB_USER }}" \
            -e DB_PWD="${{ secrets.DB_PWD }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            ${{ secrets.DOCKER_USERNAME }}/backend:latest
        EOF
